repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.260"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^.*__init__\.py$
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [src, -vvv, -i, --fail-under=80]
        exclude: ^.*__init__\.py$
        pass_filenames: false